language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "pypy"
install:
    - pip freeze
before_install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip --quiet install argparse; fi
script:
    # TODO: Replace this with a test command when tests are added
    - python -m py_compile sourglass.py
